# Generated by Django 4.1.3 on 2023-07-19 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('use_html_template', models.BooleanField(default=False)),
                ('html_template', models.FileField(blank=True, null=True, upload_to='offer_letter_templates/')),
                ('date', models.DateField()),
                ('ref_id', models.CharField(default='', max_length=20)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
