# Generated by Django 4.1.3 on 2023-08-05 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
